server:
  port: 8084

spring:
  application:
    name: gateway-routing-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/payment_platform_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    enabled: ${KAFKA_ENABLED:true}
  redis:
    enabled: ${REDIS_ENABLED:true}
